# Nome da aplicação
spring.application.name=CineTrack

# Endereço do banco de dados
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/cinetrack?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=America/Sao_Paulo}

# Usuário do MySQL
spring.datasource.username=${DB_USERNAME:root}

# Senha recebida por uma variável de ambiente.
# O valor após os dois-pontos é o padrão vazio.
spring.datasource.password=${DB_PASSWORD:root}

# Atualiza as tabelas com base nas entidades Java
spring.jpa.hibernate.ddl-auto=update

# Mostra os comandos SQL no terminal
spring.jpa.show-sql=true

# Formata os comandos SQL para facilitar a leitura
spring.jpa.properties.hibernate.format_sql=true

# Evita cache das páginas durante o desenvolvimento
spring.thymeleaf.cache=false